---
title: "Untitled"
output: html_document
date: "2024-05-01"
editor_options: 
  chunk_output_type: console
---

Load packages and make nice theme for plots
```{r}
library(foreach)
library(tidyverse)
library(viridis)

bbtheme <- theme(
  axis.text.x = element_text(size = 12, face = "bold"),
  axis.text.y = element_text(size = 12, face = "bold"),
  axis.title.x = element_text(size = 12, face = "bold"),
  axis.title.y = element_text(size = 12, face = "bold"),
  plot.title = element_text(size = 12, face = "bold"),
  strip.text = element_text(size = 12, face = "bold")
)
```

Load and process the data on true positive rate and false positive rate
```{r}
filenames <- list.files("./data")
x <- readRDS(paste0("./data/", filenames[[20]]))

i <- filenames[[1]]

data_cancer <- foreach(i = filenames, .combine = "rbind") %do% {
  x <- readRDS(paste0("./data/", i))
  data <- foreach(number = 1:length(x), .combine = "rbind") %do% {
    if (grepl("MI_PCA", i)) {
      output <- x[[number]]$error_pca %>%
        mutate(Method = "MI PCA 80%")
    } else {
      output <- rbind(x[[number]]$error_si, x[[number]]$error, x[[number]]$error_pca) %>% dplyr::select(-Predictor)
    }
    percent_name <- str_split(i, "_")
    output$mechanism <- percent_name[[1]][4]
    output$percent_missing <- str_remove(percent_name[[1]][6], ".RDS")
    output
  }
}

final_data_cancer <- data_cancer %>%
  group_by(Method, percent_missing, mechanism) %>%
  mutate(
    FPR = false_pos_ratio,
    TPR = prop_true_identifed
  ) %>%
  mutate(percent_missing = as.numeric(percent_missing)) %>%
  mutate(Dataset = "NSCLC") %>%
  mutate(Method = case_when(
    Method == "Single imputation" ~ "SI",
    Method == "Complete case" ~ "CC",
    Method == "MI PCA 80%" ~ "MI PCA 80%",
    Method == "RNAseqCovarImpute PCA" ~ "MI PCA Horn",
    Method == "RNAseqCovarImpute" ~ "MI Gene Bin"
  ))


data_mi_cancer <- final_data_cancer %>% filter(Method %in% c("MI Gene Bin", "MI PCA 80%", "MI PCA Horn"))
data_main_cancer <- final_data_cancer %>%
  filter(Method %in% c("SI", "CC", "MI PCA Horn")) %>%
  mutate(Method = ifelse(Method == "MI PCA Horn", "RNAseqCovarImpute", Method)) %>%
  mutate(Method = factor(Method, levels = c("CC", "SI", "RNAseqCovarImpute")))

data_main_cancer %>%
  group_by(mechanism, Method, percent_missing) %>%
  summarize(med = median(TPR)) %>%
  filter(percent_missing == "55")

data_main_cancer %>%
  group_by(Method, percent_missing) %>%
  summarize(
    min = min(TPR),
    max = max(TPR)
  ) %>%
  filter(percent_missing == "55")

data_main_cancer %>%
  filter(Method == "RNAseqCovarImpute") %>%
  group_by(percent_missing, mechanism) %>%
  summarize(med = median(FPR))

library(RColorBrewer)
color_palette <- brewer.pal(3, "Set1")
# these plots to compare the MI methods (Gene bin, PCA 80% var, PCA Horn)
C1 <- ggplot(data_mi_cancer, aes(x = factor(percent_missing), y = TPR, fill = Method)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitterdodge(jitter.width = 0), alpha = .5) +
  facet_wrap(~mechanism, scales = "free", nrow = 1, ncol = 3) +
  scale_y_continuous(breaks = c(.7, .8, .9, 1), limits = c(0.7, 1)) +
  scale_fill_manual(values = color_palette) +
  labs(
    y = "TPR",
    x = "Individuals with missing data (%)"
  ) +
  theme_bw() +
  bbtheme +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom")

D1 <- ggplot(data_mi_cancer, aes(x = factor(percent_missing), y = FPR, fill = Method)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitterdodge(jitter.width = 0), alpha = .5) +
  facet_wrap(~mechanism, nrow = 1, ncol = 3, scales = "free") +
  scale_y_continuous(breaks = c(.02, .05, .08), limits = c(0, .09)) +
  scale_fill_manual(values = color_palette) +
  labs(
    y = "FPR",
    x = "Individuals with missing data (%)"
  ) +
  theme_bw() +
  bbtheme +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom") +
  geom_hline(yintercept = .05, linetype = "dashed")


C1
D1



# these plots to compare the CC SI and our MI method of choice that uses Horn's parallel analysis

C2 <- ggplot(data_main_cancer, aes(x = factor(percent_missing), y = TPR, fill = Method)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitterdodge(jitter.width = 0), alpha = .5) +
  facet_wrap(~mechanism, scales = "free", nrow = 1, ncol = 3) +
  scale_y_continuous(breaks = c(0, .25, .5, .75, 1), limits = c(0, 1)) +
  scale_fill_manual(values = color_palette) +
  labs(
    y = "TPR",
    x = "Individuals with missing data (%)"
  ) +
  theme_bw() +
  bbtheme +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom")

D2 <- ggplot(data_main_cancer, aes(x = factor(percent_missing), y = FPR, fill = Method)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitterdodge(jitter.width = 0), alpha = .5) +
  facet_wrap(~mechanism, nrow = 1, ncol = 3, scales = "free") +
  scale_y_continuous(breaks = c(.05, .15, .25, .35), limits = c(0, .36)) +
  scale_fill_manual(values = color_palette) +
  labs(
    y = "FPR",
    x = "Individuals with missing data (%)"
  ) +
  theme_bw() +
  bbtheme +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom") +
  geom_hline(yintercept = .05, linetype = "dashed")


C2
D2
```

Load and process the data on mean absolute percentage error
```{r}
truth_res <- read_csv("truth_res_cancer_data_sex_age_smoking.csv")
truth_res %>%
  group_by(significant) %>%
  summarize(n = n())
filenames <- list.files("./data")

cancer_mape <- foreach(i = filenames, .combine = "rbind") %do% {
  x <- readRDS(paste0("./data/", i))
  data <- foreach(number = 1:length(x), .combine = "rbind") %do% {
    output <- x[[number]]$coefs
    percent_name <- str_split(i, "_")
    output$mechanism <- percent_name[[1]][4]
    output$percent_missing <- str_remove(percent_name[[1]][6], ".RDS")

    if (grepl("all_other_methods", i)) { # The files with this name store CC, SI, and MI PCA horn results
      output <- output %>%
        pivot_longer(
          cols = c("logFC", "logFC_si", "sexmale_coef"),
          values_to = "coef_missing",
          names_to = "Method"
        ) %>%
        mutate(Method = case_when(
          Method == "logFC" ~ "CC",
          Method == "logFC_si" ~ "SI",
          Method == "sexmale_coef" ~ "MI PCA Horn"
        ))
    }

    if (grepl("gene_bin_method", i)) { # The files with this name store MI Gene Bin results
      output <- output %>%
        mutate(Method = "MI Gene Bin") %>%
        dplyr::rename(coef_missing = coef_combined)
    }

    if (grepl("MI_PCA_80", i)) { # The files with this name store MI PCA 80% var results
      output <- output %>%
        mutate(Method = "MI PCA 80%") %>%
        dplyr::rename(coef_missing = sexmale_coef) %>%
        left_join(truth_res)
    }



    output <- output %>%
      mutate(APE = 100 * abs(coef_verify - coef_missing) / abs(coef_verify)) %>%
      group_by(mechanism, percent_missing, Method) %>%
      summarise(MAPE = mean(APE))
  }
}


cancer_mape <- cancer_mape %>%
  mutate(percent_missing = factor(percent_missing, levels = c("55", "65", "75", "85"))) %>%
  mutate(mechanism = factor(mechanism,
    levels = c("MCAR", "MAR", "MNAR")
  ))



mape_mi_cancer <- cancer_mape %>% filter(Method %in% c("MI Gene Bin", "MI PCA 80%", "MI PCA Horn"))
mape_main_cancer <- cancer_mape %>%
  filter(Method %in% c("SI", "CC", "MI PCA Horn")) %>%
  mutate(Method = ifelse(Method == "MI PCA Horn", "RNAseqCovarImpute", Method)) %>%
  mutate(Method = factor(Method, levels = c("CC", "SI", "RNAseqCovarImpute")))

B1_bias <- ggplot(mape_mi_cancer, aes(percent_missing, y = MAPE, fill = Method)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitterdodge(jitter.width = 0), alpha = .5) +
  facet_wrap(~mechanism, scales = "free", nrow = 1, ncol = 3) +
  # scale_y_continuous(breaks = c(0,.25,.5,.75,1), limits = c(0,1))+
  scale_fill_manual(values = color_palette) +
  labs(
    y = "MAPE",
    x = "Individuals with missing data (%)"
  ) +
  theme_bw() +
  bbtheme +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom")

B2_bias <- ggplot(mape_main_cancer, aes(percent_missing, y = MAPE, fill = Method)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitterdodge(jitter.width = 0), alpha = .5) +
  facet_wrap(~mechanism, scales = "free", nrow = 1, ncol = 3) +
  # scale_y_continuous(breaks = c(0,.25,.5,.75,1), limits = c(0,1))+
  scale_fill_manual(values = color_palette) +
  labs(
    y = "MAPE",
    x = "Individuals with missing data (%)"
  ) +
  theme_bw() +
  bbtheme +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom")
```

Final plots
```{r}
library(ggpubr)
# Plot for the main text comparing CC, SI and MI PCA Horn
p1 <- ggarrange(C2 + theme(axis.title.x = element_blank()),
  D2 + theme(axis.title.x = element_blank()),
  B2_bias + theme(axis.title.x = element_blank()),
  common.legend = T, nrow = 3, ncol = 1,
  labels = c("A", "B", "C")
)

jpeg(filename = "impute figure NSCLC data.jpg", res = 600, width = 15, height = 15, units = "in")
annotate_figure(p1,
  bottom = text_grob("Individuals with missing data (%)", size = 20, face = "bold"),
  top = text_grob("NSCLC Dataset", size = 20, face = "bold")
)
dev.off()


# Plot for the supplement comparing MI Gene Bin, MI PCA Horn, and MI PCA 80%
p1 <- ggarrange(C1 + theme(axis.title.x = element_blank()),
  D1 + theme(axis.title.x = element_blank()),
  B1_bias + theme(axis.title.x = element_blank()),
  common.legend = T, nrow = 3, ncol = 1,
  labels = c("A", "B", "C")
)

jpeg(filename = "impute figure NSCLC data supplement.jpg", res = 600, width = 15, height = 15, units = "in")
annotate_figure(p1,
  bottom = text_grob("Individuals with missing data (%)", size = 20, face = "bold"),
  top = text_grob("NSCLC Dataset", size = 20, face = "bold")
)
dev.off()
```

